### ISSUE TITLE
Release on GitHub?

### ISSUE THREAD

**Issue by Indigo744** [jslegers/cascadeframework#89]
Hello,

I use Cascade Framework regularly on several projects and I love it. 

However, I was wondering why you weren't tagging your releases on GitHub?
This would be really useful for us to see the evolution and the list of commit regarding a specific release.

Talking about evolutions, there is sadly no changelog available. Do you plan adding one? 

Thanks a lot. Best wishes.

Guillaume.

**Comment by jslegers** [comment]
> I use Cascade Framework regularly on several projects and I love it.

Thanks. I'd love to see what you've done with it!

> However, I was wondering why you weren't tagging your releases on GitHub?

Time constraints is the major reason. Cascade Framework is pretty much a one-man project and maintained (mostly in my spare time) in between customer projects and other open source projects (eg. my [PHP framework](https://github.com/PHPPowertools)).

> Talking about evolutions, there is sadly no changelog available. Do you plan adding one?

I don't think it's useful to add a changelog for Cascade Framework 1.x at this stage, as subsequent releases will be bugfixes and minor improvements only.

Cascade Framework 2.x will involve a redesign of all components, an addition of new components and will be written in SCSS. I will add a changelog with the release of Cascade Framework 2.x.

**Comment by Indigo744** [comment]
Thanks a lot for your clarification !
I will post links as soon as my projects are out in the sun ! I'll let you know ;-)
